### ISSUE TITLE
Please print file/directory names when failing to read

### ISSUE THREAD

**Issue by BCMM** [sammhicks/internet-radio-rs#27]
It would be much easier to diagnose certain misconfigurations if, when printing "Failed to read" errors, rradio also printed the name of the file or directory it had tried to read (particularly as I don't currently have strace available on-device).

I have had this issue with the config file and with the stations directory. I tried to write a patch but I don't seem to have enough grasp on the type system to turn a path in to a printable string.

**Comment by sammhicks** [comment]
Resolved by 19e53169839e11b896a33e086f168789b6628ae9
